syntax = "proto2";
package xiaomi;
option java_package = "nodomain.freeyourgadget.gadgetbridge.proto.xiaomi";
option java_multiple_files = true;

message Watchface {
  optional WatchfaceList watchfaceList = 1;

  // 4, 2 delete | 4, 1 set
  optional string watchfaceId = 2;
  optional uint32 ack = 4; // 1

  // 4, 4
  optional uint32 installStatus = 5; // 0 not installed, 2 already installed
  optional WatchfaceInstallStart watchfaceInstallStart = 6;
  optional WatchfaceInstallFinish watchfaceInstallFinish = 7;
}

message WatchfaceList {
  repeated WatchfaceInfo watchface = 1;
}

message WatchfaceInfo {
  optional string id = 1;
  optional string name = 2;
  optional bool active = 3;
  optional bool canDelete = 4;
  optional uint32 unknown5 = 5; // 0
  optional uint32 unknown6 = 6; // 0
  optional uint32 unknown11 = 11; // 0
}

message WatchfaceInstallStart {
  optional string id = 1;
  optional uint32 size = 2;
}

message WatchfaceInstallFinish {
  optional string id = 1;
  optional uint32 unknown2 = 2; // 2
  optional uint32 unknown3 = 3; // 0
  optional uint32 unknown4 = 4; // 0
}
