syntax = "proto2";
package xiaomi;
option java_package = "nodomain.freeyourgadget.gadgetbridge.proto.xiaomi";
option java_multiple_files = true;
import "xiaomi/wear_common.proto";

message Schedule {
  // 17, 0 get
  optional Alarms alarms = 1;
  // 17, 1
  optional AlarmDetails createAlarm = 2;
  // 17, 3 -> returns 17, 5
  optional AlarmInfo editAlarm = 3;

  optional uint32 ackId = 4; // id of created or edited alarm and reminder

  // 17, 4
  optional AlarmDelete deleteAlarm = 5;

  // 17, 8 get | 17, 9 set
  optional SleepMode sleepMode = 9;

  // 17, 14 get: 10 -> 2: 50 // max reminders?
  optional Reminders reminders = 10;

  // 17,10 get/ret | 17,11 create | 17,13 delete
  optional WorldClocks worldClocks = 11;

  optional uint32 worldClockStatus = 13; // 0 on edit and create

  // 17, 15
  optional ReminderDetails createReminder = 14;

  // 17, 17
  optional ReminderInfo editReminder = 15;

  // 17, 18
  optional ReminderDelete deleteReminder = 17;
}

message Alarms {
  optional uint32 maxAlarms = 2; // 10
  optional uint32 unknown3 = 3; // 0
  optional uint32 unknown4 = 4; // 1
  repeated AlarmInfo alarm = 1;
}

message AlarmInfo {
  optional uint32 id = 1; // starts at 1
  optional AlarmDetails alarmDetails = 2;
}

message AlarmDetails {
  optional HourMinute time = 2;
  optional uint32 repeatMode = 3; // 0 once, 1 daily, 5 weekly
  optional uint32 repeatFlags = 4; // only if weekly: 31 during week, 1 monday, 2 tuesday, 3 mon tue
  optional bool enabled = 5;
  optional uint32 smart = 7; // 1 smart, 2 normal
}

message AlarmDelete {
  repeated uint32 id = 1;
}

message SleepMode {
  required bool enabled = 1;
  optional SleepModeSchedule schedule = 2;
}

message SleepModeSchedule {
  optional HourMinute start = 1;
  optional HourMinute end = 2;
  optional uint32 unknown3 = 3; // 0
}

message Reminders {
  repeated ReminderInfo reminder = 1;
  optional uint32 maxReminders = 2;
}

message ReminderInfo {
  optional uint32 id = 1;
  optional ReminderDetails reminderDetails = 2;
}

message ReminderDetails {
  optional Date date = 1;
  optional Time time = 2;
  optional uint32 repeatMode = 3; // 0 once, 1 daily, weekly (every monday), 7 monthly, 8 yearly
  optional uint32 repeatFlags = 4; // 64 for unset, day flags on weekly
  optional string title = 5;
}

message ReminderDelete {
  repeated uint32 id = 1;
}

message WorldClocks {
  repeated string worldClock = 1;
}
